# Generated by Django 4.2.1 on 2024-06-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_tagpost_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagpost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='tagpost',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagPost',
        ),
    ]
